$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/avmm_cdc/sim/../st_dc_fifo_1941/sim/avmm_cdc_st_dc_fifo_1941_t2zlahy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/avmm_cdc/sim/../st_dc_fifo_1941/sim/altera_reset_synchronizer.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/avmm_cdc/sim/../st_dc_fifo_1941/sim/altera_dcfifo_synchronizer_bundle.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/avmm_cdc/sim/../st_dc_fifo_1941/sim/altera_std_synchronizer_nocut.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/avmm_cdc/sim/../mm_ccb_1921/sim/avmm_cdc_mm_ccb_st_dc_fifo_1921_vmo4e5i.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/avmm_cdc/sim/../mm_ccb_1921/sim/avmm_cdc_mm_ccb_st_dc_fifo_1921_ralj33q.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/avmm_cdc/sim/../mm_ccb_1921/sim/avmm_cdc_mm_ccb_1921_qyktlaq.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/avmm_cdc/sim/avmm_cdc.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/avmm_pipeline_bridge/sim/../altera_avalon_mm_bridge_2001/sim/avmm_pipeline_bridge_altera_avalon_mm_bridge_2001_qvaevxa.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/avmm_pipeline_bridge/sim/avmm_pipeline_bridge.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/emif_ddr4_no_ecc_altera_emif_arch_nd_191_iocy4qa_top.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/emif_ddr4_no_ecc_altera_emif_arch_nd_191_iocy4qa_io_ssm.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_bufs.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_buf_udir_se_i.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_buf_udir_se_o.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_buf_udir_df_i.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_buf_udir_df_o.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_buf_udir_cp_i.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_buf_bdir_df.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_buf_bdir_se.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_buf_unused.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_cal_counter.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_emif2mem.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_pll.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_pll_fast_sim.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_pll_extra_clks.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_oct.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_core_clks_rsts.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_hps_clks_rsts.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_local_reset.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_io_tiles_wrap.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_io_tiles.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_io_tiles_abphy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_abphy_mux.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_io_lane_remap.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_io_lane_remap_abphy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_hmc_avl_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_hmc_sideband_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_hmc_mmr_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_hmc_amm_data_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_phylite_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_hmc_ast_data_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_afi_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_seq_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_emif_arch_nd_regs.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_oct.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/altera_oct_um_fsm.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/mem_array_abphy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/fourteennm_io_12_lane_abphy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/fourteennm_io_12_lane_encrypted_abphy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/fourteennm_io_12_lane_mdev40_encrypted_abphy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/io_12_lane__mdev40_abphy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_arch_nd_191/sim/emif_ddr4_no_ecc_altera_emif_arch_nd_191_iocy4qa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/../altera_emif_s10_1925/sim/emif_ddr4_no_ecc_altera_emif_s10_1925_22bjj2a.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/ip/emif_ddr4_no_ecc/sim/emif_ddr4_no_ecc.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../../ip/ofs_ddr_axi_bridge/amm_clock/sim//amm_clock.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../../ip/ofs_ddr_axi_bridge/amm_reset/sim//amm_reset.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../../ip/ofs_ddr_axi_bridge/axi_ep/sim//../ddr_axi_master_endpoint_10/sim/ddr_axi_master_endpoint.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../../ip/ofs_ddr_axi_bridge/axi_ep/sim//../ddr_axi_master_endpoint_10/sim/ofs_pipeline_reg.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../../ip/ofs_ddr_axi_bridge/axi_ep/sim//axi_ep.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../../ip/ofs_ddr_axi_bridge/avmm_ep/sim//../ddr_avmm_slave_endpoint_10/sim/ddr_avmm_slave_endpoint.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../../ip/ofs_ddr_axi_bridge/avmm_ep/sim//avmm_ep.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_axi_translator_1921/sim/ofs_ddr_axi_bridge_altera_merlin_axi_translator_1921_uetfduq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_slave_translator_191/sim/ofs_ddr_axi_bridge_altera_merlin_slave_translator_191_x56fcki.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_burst_adapter_1923/sim/altera_merlin_address_alignment.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_axi_master_ni_1940/sim/ofs_ddr_axi_bridge_altera_merlin_axi_master_ni_1940_xmlitzq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_slave_agent_191/sim/ofs_ddr_axi_bridge_altera_merlin_slave_agent_191_ncfkfri.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_slave_agent_191/sim/altera_merlin_burst_uncompressor.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_avalon_sc_fifo_1931/sim/ofs_ddr_axi_bridge_altera_avalon_sc_fifo_1931_vhmcgqy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_router_1921/sim/ofs_ddr_axi_bridge_altera_merlin_router_1921_rjd76li.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_router_1921/sim/ofs_ddr_axi_bridge_altera_merlin_router_1921_d4nhvri.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_avalon_st_pipeline_stage_1920/sim/ofs_ddr_axi_bridge_altera_avalon_st_pipeline_stage_1920_zterisq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_avalon_st_pipeline_stage_1920/sim/altera_avalon_st_pipeline_base.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_burst_adapter_1923/sim/ofs_ddr_axi_bridge_altera_merlin_burst_adapter_altera_avalon_st_pipeline_stage_1923_lnv6wky.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_burst_adapter_1923/sim/ofs_ddr_axi_bridge_altera_merlin_burst_adapter_1923_kxay2pi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_burst_adapter_1923/sim/altera_merlin_burst_adapter_uncmpr.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_burst_adapter_1923/sim/altera_merlin_burst_adapter_13_1.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_burst_adapter_1923/sim/altera_merlin_burst_adapter_new.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_burst_adapter_1923/sim/altera_incr_burst_converter.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_burst_adapter_1923/sim/altera_wrap_burst_converter.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_burst_adapter_1923/sim/altera_default_burst_converter.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_demultiplexer_1921/sim/ofs_ddr_axi_bridge_altera_merlin_demultiplexer_1921_frmnpai.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_multiplexer_1921/sim/ofs_ddr_axi_bridge_altera_merlin_multiplexer_1921_y2amuty.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_multiplexer_1921/sim/altera_merlin_arbitrator.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_demultiplexer_1921/sim/ofs_ddr_axi_bridge_altera_merlin_demultiplexer_1921_z7ubwna.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_merlin_multiplexer_1921/sim/ofs_ddr_axi_bridge_altera_merlin_multiplexer_1921_cuucplq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/../altera_mm_interconnect_1920/sim/ofs_ddr_axi_bridge_altera_mm_interconnect_1920_k26veqi.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/mem/axi_bridge/ofs_ddr_axi_bridge/sim/ofs_ddr_axi_bridge.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_tx_xcvr_half_clk/sim//address_decode_tx_xcvr_half_clk.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_tx_xcvr_clk/sim//address_decode_tx_xcvr_clk.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_rx_xcvr_clk/sim//address_decode_rx_xcvr_clk.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_mm_to_phy/sim//../altera_merlin_slave_translator_191/sim/address_decode_mm_to_phy_altera_merlin_slave_translator_191_x56fcki.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_mm_to_phy/sim//address_decode_mm_to_phy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_clk_csr/sim//address_decode_clk_csr.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_jtag_dc_streaming_191/sim/altera_avalon_st_jtag_interface.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_jtag_dc_streaming_191/sim/altera_jtag_dc_streaming.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_jtag_dc_streaming_191/sim/altera_jtag_sld_node.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_jtag_dc_streaming_191/sim/altera_jtag_streaming.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_jtag_dc_streaming_191/sim/altera_avalon_st_clock_crosser.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_jtag_dc_streaming_191/sim/altera_avalon_st_idle_remover.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_jtag_dc_streaming_191/sim/altera_avalon_st_idle_inserter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_jtag_dc_streaming_191/sim/altera_avalon_st_pipeline_stage.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../timing_adapter_1930/sim/address_decode_master_0_timing_adapter_1930_zznpvoa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_avalon_sc_fifo_1931/sim/address_decode_master_0_altera_avalon_sc_fifo_1931_fzgstwy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_avalon_st_bytes_to_packets_1920/sim/altera_avalon_st_bytes_to_packets.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_avalon_st_packets_to_bytes_1920/sim/altera_avalon_st_packets_to_bytes.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_avalon_packets_to_master_1920/sim/altera_avalon_packets_to_master.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../channel_adapter_1921/sim/address_decode_master_0_channel_adapter_1921_5wnzrci.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../channel_adapter_1921/sim/address_decode_master_0_channel_adapter_1921_fkajlia.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_reset_controller_1921/sim/altera_reset_controller.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//../altera_jtag_avalon_master_191/sim/address_decode_master_0_altera_jtag_avalon_master_191_3zppvky.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_master_0/sim//address_decode_master_0.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_merlin_master_translator_0/sim//../altera_merlin_master_translator_191/sim/address_decode_merlin_master_translator_0_altera_merlin_master_translator_191_g7h47bq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_merlin_master_translator_0/sim//address_decode_merlin_master_translator_0.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_mm_to_mac/sim//../altera_merlin_slave_translator_191/sim/address_decode_mm_to_mac_altera_merlin_slave_translator_191_x56fcki.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../../ip/address_decode/address_decode_mm_to_mac/sim//address_decode_mm_to_mac.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_master_translator_191/sim/address_decode_altera_merlin_master_translator_191_g7h47bq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_slave_translator_191/sim/address_decode_altera_merlin_slave_translator_191_x56fcki.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_master_agent_191/sim/address_decode_altera_merlin_master_agent_191_mpbm6tq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_slave_agent_191/sim/address_decode_altera_merlin_slave_agent_191_ncfkfri.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_avalon_sc_fifo_1931/sim/address_decode_altera_avalon_sc_fifo_1931_fzgstwy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_router_1921/sim/address_decode_altera_merlin_router_1921_ful5neq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_router_1921/sim/address_decode_altera_merlin_router_1921_ctyhtgi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_traffic_limiter_191/sim/address_decode_altera_merlin_traffic_limiter_altera_avalon_sc_fifo_191_vxkzyii.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_traffic_limiter_191/sim/altera_merlin_reorder_memory.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_traffic_limiter_191/sim/address_decode_altera_merlin_traffic_limiter_191_kcba44q.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_avalon_st_pipeline_stage_1920/sim/address_decode_altera_avalon_st_pipeline_stage_1920_zterisq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_burst_adapter_1923/sim/address_decode_altera_merlin_burst_adapter_altera_avalon_st_pipeline_stage_1923_itc7ppy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_burst_adapter_1923/sim/address_decode_altera_merlin_burst_adapter_1923_5bnc2dy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_demultiplexer_1921/sim/address_decode_altera_merlin_demultiplexer_1921_54oeqsi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_multiplexer_1921/sim/address_decode_altera_merlin_multiplexer_1921_cmcbhqi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_demultiplexer_1921/sim/address_decode_altera_merlin_demultiplexer_1921_uzs3tbq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_merlin_multiplexer_1921/sim/address_decode_altera_merlin_multiplexer_1921_w3sjzzi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/../altera_mm_interconnect_1920/sim/address_decode_altera_mm_interconnect_1920_g5rwjti.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/address_decoder/address_decode/sim/address_decode.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/alt_em10g32.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/alt_em10g32unit.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_clk_rst.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_clock_crosser.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_crc32.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_crc32_gf_mult32_kc.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_creg_map.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_creg_top.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_frm_decoder.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_rs_gmii_mii_layer.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_pipeline_base.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_reset_synchronizer.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rr_clock_crosser.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rst_cnt.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_fctl_filter_crcpad_rem.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_fctl_overflow.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_fctl_preamble.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_frm_control.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_pfc_flow_control.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_pfc_pause_conversion.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_pkt_backpressure_control.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_rs_gmii16b.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_rs_gmii16b_top.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_rs_gmii_mii.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_rs_layer.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_rs_xgmii.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_status_aligner.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_top.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_stat_mem.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_stat_reg.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_data_frm_gen.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_srcaddr_inserter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_err_aligner.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_flow_control.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_frm_arbiter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_frm_muxer.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_pause_beat_conversion.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_pause_frm_gen.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_pause_req.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_pfc_frm_gen.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rr_buffer.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_rs_gmii16b.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_rs_gmii16b_top.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_rs_layer.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_rs_xgmii_layer.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_sc_fifo.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_top.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_gmii_decoder.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_gmii_decoder_dfa.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_gmii_encoder.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_gmii_encoder_dfa.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_gmii_mii_decoder_if.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_gmii_mii_encoder_if.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_avalon_mm_adapter/altera_eth_avalon_mm_adapter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_avalon_st_adapter/altera_eth_avalon_st_adapter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_avalon_st_adapter/avalon_st_adapter_avalon_st_rx.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_avalon_st_adapter/avalon_st_adapter_avalon_st_tx.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_avalon_st_adapter/avalon_st_adapter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_avalon_st_adapter/alt_em10g32_vldpkt_rddly.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_avalon_st_adapter/sideband_adapter_rx.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_avalon_st_adapter/sideband_adapter_tx.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_avalon_st_adapter/sideband_adapter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_avalon_st_adapter/altera_eth_sideband_crosser.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_avalon_st_adapter/altera_eth_sideband_crosser_sync.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_xgmii_width_adaptor/alt_em10g_32_64_xgmii_conversion.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_xgmii_width_adaptor/alt_em10g_32_to_64_xgmii_conversion.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_xgmii_width_adaptor/alt_em10g_64_to_32_xgmii_conversion.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_xgmii_width_adaptor/alt_em10g_dcfifo_32_to_64_xgmii_conversion.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_xgmii_width_adaptor/alt_em10g_dcfifo_64_to_32_xgmii_conversion.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_xgmii_data_format_adapter/alt_em10g32_xgmii_32_to_64_adapter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_xgmii_data_format_adapter/alt_em10g32_xgmii_64_to_32_adapter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/adapters/altera_eth_xgmii_data_format_adapter/alt_em10g32_xgmii_data_format_adapter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_altsyncram_bundle.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_altsyncram.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_avalon_dc_fifo_lat_calc.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_avalon_dc_fifo_hecc.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_avalon_dc_fifo_secc.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_avalon_sc_fifo.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_avalon_sc_fifo_hecc.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_avalon_sc_fifo_secc.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_ecc_dec_18_12.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_ecc_dec_39_32.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_ecc_enc_12_18.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_ecc_enc_32_39.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_rs_xgmii_layer_ultra.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_rs_xgmii_ultra.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_avst_to_gmii_if.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_gmii_to_avst_if.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_gmii_tsu.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_gmii16b_tsu.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_lpm_mult.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_ptp_aligner.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_ptp_detector.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_rx_ptp_top.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_gmii_crc_inserter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_gmii16b_crc_inserter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_gmii_ptp_inserter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_gmii16b_ptp_inserter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_gmii16b_ptp_inserter_1g2p5g10g.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_ptp_processor.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_ptp_top.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_xgmii_crc_inserter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_tx_xgmii_ptp_inserter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_xgmii_tsu.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_crc328generator.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_crc32ctl8.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_crc32galois8.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_gmii_crc_inserter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_gmii16b_crc_inserter.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/synopsys/rtl/alt_em10g32_gmii16b_crc32.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/alt_em10g32_avalon_dc_fifo.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/alt_em10g32_dcfifo_synchronizer_bundle.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/../alt_em10g32_2100/sim/alt_em10g32_std_synchronizer.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/mac/altera_eth_10g_mac/sim/altera_eth_10g_mac.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/altera_xcvr_native_s10_functions_h.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_arbiter.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_resync_std.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_reset_counter_s10.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/s10_avmm_h.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_avmm_csr.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_prbs_accum.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_odi_accel.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_arb.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_early_spd_chng_s10_htile.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_anlg_reset_seq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_dig_reset_seq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_reset_seq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_anlg_reset_seq_wrapper.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_re_cal_chnl.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_pcie_rx_eios_prot.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rx_maib_wa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/altera_eth_10gbaser_phy_altera_xcvr_native_s10_htile_1930_nld7qsi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_nld7qsi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/phy/altera_eth_10gbaser_phy/sim/altera_eth_10gbaser_phy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/pll_atxpll/altera_xcvr_atx_pll_ip/sim/../altera_xcvr_atx_pll_s10_htile_1911/sim/alt_xcvr_resync.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/pll_atxpll/altera_xcvr_atx_pll_ip/sim/../altera_xcvr_atx_pll_s10_htile_1911/sim/alt_xcvr_pll_rcfg_arb.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/pll_atxpll/altera_xcvr_atx_pll_ip/sim/../altera_xcvr_atx_pll_s10_htile_1911/sim/alt_xcvr_pll_embedded_debug.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/pll_atxpll/altera_xcvr_atx_pll_ip/sim/../altera_xcvr_atx_pll_s10_htile_1911/sim/alt_xcvr_pll_avmm_csr.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/pll_atxpll/altera_xcvr_atx_pll_ip/sim/../altera_xcvr_atx_pll_s10_htile_1911/sim/altera_xcvr_atx_pll_ip_altera_xcvr_atx_pll_s10_htile_1911_iwnldza.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/pll_atxpll/altera_xcvr_atx_pll_ip/sim/../altera_xcvr_atx_pll_s10_htile_1911/sim/alt_xcvr_pll_rcfg_opt_logic_iwnldza.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/pll_atxpll/altera_xcvr_atx_pll_ip/sim/altera_xcvr_atx_pll_ip.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/pll_mpll/pll/sim/../altera_xcvr_fpll_s10_htile_1912/sim/pll_altera_xcvr_fpll_s10_htile_1912_jqxz7ny.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/pll_mpll/pll/sim/../altera_xcvr_fpll_s10_htile_1912/sim/alt_xcvr_pll_rcfg_opt_logic_jqxz7ny.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/pll_mpll/pll/sim/pll.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/xcvr_reset_controller/reset_control/sim/../altera_xcvr_reset_control_s10_1911/sim/altera_xcvr_reset_control_s10.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/hssi/s10/ip/xcvr_reset_controller/reset_control/sim/reset_control.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_cbhmiqa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_cbhmiqa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_n4y2kuq.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_jzbmjyy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_jzbmjyy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_bx66sci.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_gvo5t4y.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_gvo5t4y.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_oyvoy3a.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_gyzglqa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_gyzglqa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_6usotiq.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_dnoikia.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_dnoikia.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_62r7t6q.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_yechdri.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_yechdri.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_wyjegcy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_4d6lwki.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_4d6lwki.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_dibf4ky.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_git6cpy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_git6cpy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_t3zhjty.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_v5bgqya.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_v5bgqya.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_duuecai.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_mifbr3y.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_mifbr3y.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_qtzt76q.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_s5p5c4i.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_s5p5c4i.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_2ko7bza.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_qaqcpqa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_qaqcpqa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_quozwsi.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_mpnr4ca.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_mpnr4ca.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_lrgozwq.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_yhlclwi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_yhlclwi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_mw57i4a.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_j6u4yci.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_j6u4yci.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_xoxt4yi.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/pcie_ep_g3x16_altera_xcvr_native_s10_htile_1930_sobbjjq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_native_s10_htile_1930/sim/alt_xcvr_native_rcfg_opt_logic_sobbjjq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_altera_xcvr_native_s10_htile_191_qkrgq3y.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_pcie_hip_native_s10_191/sim/pcie_ep_g3x16_altera_xcvr_pcie_hip_native_s10_191_rgbka6i.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/pcie_ep_g3x16_altera_pcie_s10_hip_ast_altera_xcvr_pcie_hip_native_s10_2300_azd6m2a.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_fpll_s10_htile_1912/sim/pcie_ep_g3x16_altera_xcvr_fpll_s10_htile_1912_o6x6lyi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_fpll_s10_htile_1912/sim/alt_xcvr_pll_rcfg_opt_logic_o6x6lyi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/pcie_ep_g3x16_altera_pcie_s10_hip_ast_altera_xcvr_fpll_s10_htile_2300_xikmzfi.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_atx_pll_s10_htile_1911/sim/pcie_ep_g3x16_altera_xcvr_atx_pll_s10_htile_1911_yayb5sy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_xcvr_atx_pll_s10_htile_1911/sim/alt_xcvr_pll_rcfg_opt_logic_yayb5sy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/pcie_ep_g3x16_altera_pcie_s10_hip_ast_altera_xcvr_atx_pll_s10_htile_2300_5vh66kq.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_iopll_1931/sim/pcie_ep_g3x16_altera_iopll_1931_dnmqhta.vo
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_iopll_1931/sim/stratix10_altera_iopll.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_ep_g3x16_avst512_io_pll_s10.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_hip_ast_2300_c5ifiry.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_hip_ast_pllnphy_2300_c5ifiry.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_hip_ast_pipen1b_2300_c5ifiry.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_reset_delay_sync.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_sc_bitsync.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_gen3x16_adapter.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_gen3x16_cfg_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_gen3x16_credit_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_gen3x16_err_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_gen3x16_misc_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_gen3x16_rx_st_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/alt_mlab.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/sync_pulse.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/sync_rst_n.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/sync_vec.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_gen3x16_dcfifo.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_gen3x16_gpx3.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_gen3x16_tx_st_if.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/sync_bit.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_bridge.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_dataflow.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_vf_ats_cap.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_vf_enable_init.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_vf_error_rep_fifo.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_vf_error_status_fifo.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_vf_msix_cap.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_vf_pci_cmd_reg.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_vf_pci_status_reg.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_vf_regset.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_vf_status_array.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_vf_tph_req_cap.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_cfg_vf_trans_pend_status_array.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_cfg_vf_pend_reset.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_cfg_vf_pend_flr.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_cfg_vf_pend_flr_release.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_register_ram.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/altera_pcie_s10_sriov_top.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/async_fifo.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/ceb_sync.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/cpl_pending_status_sync.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/error_status_sync.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/flr_sync.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/pf_update_sync.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/sriov_extensible_interface_cdc.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/../altera_pcie_s10_hip_ast_2300/sim/synopsys/altera_pcie_s10_sriov_bridge/two_stage_sync.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ipss/pcie/qip/pcie_ep_g3x16/sim/pcie_ep_g3x16.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_clock_bridge/sim//apf_clock_bridge.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_st2mm_slv/sim//../axi4lite_shim_10/sim/axi4lite_shim.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_pgsk_slv/sim//apf_pgsk_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_reset_bridge/sim//apf_reset_bridge.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_bpf_mst/sim//apf_bpf_mst.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_rsv_c_slv/sim//apf_rsv_c_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_rsv_b_slv/sim//apf_rsv_b_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_rsv_d_slv/sim//apf_rsv_d_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_achk_slv/sim//apf_achk_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_st2mm_mst/sim//apf_st2mm_mst.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_bpf_slv/sim//apf_bpf_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_rsv_f_slv/sim//apf_rsv_f_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_rsv_e_slv/sim//apf_rsv_e_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../../ip/apf/apf_st2mm_slv/sim//apf_st2mm_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_axi_master_ni_1940/sim/apf_altera_merlin_axi_master_ni_1940_xmlitzq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_avalon_sc_fifo_1931/sim/apf_altera_avalon_sc_fifo_1931_fzgstwy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_axi_slave_ni_1940/sim/apf_altera_merlin_axi_slave_ni_altera_avalon_sc_fifo_1940_gkp52da.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_axi_slave_ni_1940/sim/apf_altera_merlin_axi_slave_ni_1940_nt6mpli.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_axi_slave_ni_1940/sim/apf_altera_merlin_axi_slave_ni_1940_sk7woda.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_axi_slave_ni_1940/sim/apf_altera_merlin_axi_slave_ni_1940_ho2e2tq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_axi_slave_ni_1940/sim/apf_altera_merlin_axi_slave_ni_1940_5ufntci.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_axi_slave_ni_1940/sim/apf_altera_merlin_axi_slave_ni_1940_gxd3cey.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_axi_slave_ni_1940/sim/apf_altera_merlin_axi_slave_ni_1940_qd2xb6q.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_axi_slave_ni_1940/sim/apf_altera_merlin_axi_slave_ni_1940_zavtzra.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_axi_slave_ni_1940/sim/apf_altera_merlin_axi_slave_ni_1940_dnrwv6a.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_axi_slave_ni_1940/sim/apf_altera_merlin_axi_slave_ni_1940_6wufkqa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_router_1921/sim/apf_altera_merlin_router_1921_jj7niei.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_router_1921/sim/apf_altera_merlin_router_1921_u372lua.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_router_1921/sim/apf_altera_merlin_router_1921_if4bkjq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_router_1921/sim/apf_altera_merlin_router_1921_ez2mjlq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_router_1921/sim/apf_altera_merlin_router_1921_cymfb6a.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_router_1921/sim/apf_altera_merlin_router_1921_qmk6shq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_router_1921/sim/apf_altera_merlin_router_1921_dtfps2i.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_router_1921/sim/apf_altera_merlin_router_1921_bqnvpja.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_traffic_limiter_191/sim/apf_altera_merlin_traffic_limiter_altera_avalon_sc_fifo_191_3y3wiqy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_traffic_limiter_191/sim/apf_altera_merlin_traffic_limiter_191_kcba44q.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_demultiplexer_1921/sim/apf_altera_merlin_demultiplexer_1921_ilfjdca.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_demultiplexer_1921/sim/apf_altera_merlin_demultiplexer_1921_tdulorq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_multiplexer_1921/sim/apf_altera_merlin_multiplexer_1921_ncf7lpi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_multiplexer_1921/sim/apf_altera_merlin_multiplexer_1921_2mbzlba.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_demultiplexer_1921/sim/apf_altera_merlin_demultiplexer_1921_tyfzkzi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_multiplexer_1921/sim/apf_altera_merlin_multiplexer_1921_cb237dq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_merlin_multiplexer_1921/sim/apf_altera_merlin_multiplexer_1921_yqrwwla.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/../altera_mm_interconnect_1920/sim/apf_altera_mm_interconnect_1920_6jidkgi.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/apf/sim/apf.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_hssi_slv/sim//bpf_hssi_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_fme_slv/sim//bpf_fme_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_apf_slv/sim//bpf_apf_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_pcie_slv/sim//bpf_pcie_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_fme_mst/sim//bpf_fme_mst.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_rsv_6_slv/sim//bpf_rsv_6_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_clock_bridge/sim//bpf_clock_bridge.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_rsv_7_slv/sim//bpf_rsv_7_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_apf_mst/sim//bpf_apf_mst.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_reset_bridge/sim//bpf_reset_bridge.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_rsv_5_slv/sim//bpf_rsv_5_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_pmci_slv/sim//bpf_pmci_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../../ip/bpf/bpf_emif_slv/sim//bpf_emif_slv.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_axi_master_ni_1940/sim/bpf_altera_merlin_axi_master_ni_1940_xmlitzq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_avalon_sc_fifo_1931/sim/bpf_altera_avalon_sc_fifo_1931_fzgstwy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_axi_slave_ni_1940/sim/bpf_altera_merlin_axi_slave_ni_altera_avalon_sc_fifo_1940_iak5qwi.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_axi_slave_ni_1940/sim/bpf_altera_merlin_axi_slave_ni_1940_vt3tmey.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_axi_slave_ni_1940/sim/bpf_altera_merlin_axi_slave_ni_1940_hmeuiia.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_axi_slave_ni_1940/sim/bpf_altera_merlin_axi_slave_ni_1940_kohoieq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_axi_slave_ni_1940/sim/bpf_altera_merlin_axi_slave_ni_1940_hlncguy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_axi_slave_ni_1940/sim/bpf_altera_merlin_axi_slave_ni_1940_gewkjya.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_axi_slave_ni_1940/sim/bpf_altera_merlin_axi_slave_ni_1940_q2ubucq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_axi_slave_ni_1940/sim/bpf_altera_merlin_axi_slave_ni_1940_svqrfjq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_axi_slave_ni_1940/sim/bpf_altera_merlin_axi_slave_ni_1940_2vhphui.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_router_1921/sim/bpf_altera_merlin_router_1921_6srexxa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_router_1921/sim/bpf_altera_merlin_router_1921_ulsqvoi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_router_1921/sim/bpf_altera_merlin_router_1921_q4t3fzq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_router_1921/sim/bpf_altera_merlin_router_1921_2xiplwa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_traffic_limiter_191/sim/bpf_altera_merlin_traffic_limiter_altera_avalon_sc_fifo_191_3y3wiqy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_traffic_limiter_191/sim/bpf_altera_merlin_traffic_limiter_191_kcba44q.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_demultiplexer_1921/sim/bpf_altera_merlin_demultiplexer_1921_pwrbqhq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_multiplexer_1921/sim/bpf_altera_merlin_multiplexer_1921_wnarmqa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_demultiplexer_1921/sim/bpf_altera_merlin_demultiplexer_1921_ej7tc2q.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_merlin_multiplexer_1921/sim/bpf_altera_merlin_multiplexer_1921_qon7f7i.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/../altera_mm_interconnect_1920/sim/bpf_altera_mm_interconnect_1920_gpcx4aq.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/fabric/bpf/sim/bpf.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/spi_bridge/spi_bridge/sim/../../ip/spi_bridge/spi_bridge_spi_0/sim//../altera_avalon_spi_1920/sim/spi_bridge_spi_0_altera_avalon_spi_1920_qbjlcwq.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/spi_bridge/spi_bridge/sim/../../ip/spi_bridge/spi_bridge_spi_0/sim//spi_bridge_spi_0.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/spi_bridge/spi_bridge/sim/../../ip/spi_bridge/spi_bridge_clock_in/sim//spi_bridge_clock_in.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/spi_bridge/spi_bridge/sim/../../ip/spi_bridge/spi_bridge_reset_in/sim//spi_bridge_reset_in.v
$OFS_ROOTDIR/sim/scripts/qip_gen/src/pd_qsys/spi_bridge/spi_bridge/sim/spi_bridge.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/common/fme_id_rom/fme_id_rom/sim/../intel_mce_arb_100/sim/sim_dummy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/common/fme_id_rom/fme_id_rom/sim/../rom_1port_2010/sim/fme_id_rom_rom_1port_intel_mce_2010_ogfsa5i.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/common/fme_id_rom/fme_id_rom/sim/../rom_1port_2010/sim/fme_id_rom_rom_1port_intel_mce_arb_2010_t64g6ua.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/common/fme_id_rom/fme_id_rom/sim/../rom_1port_2010/sim/fme_id_rom_rom_1port_2010_btxr7ia.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/common/fme_id_rom/fme_id_rom/sim/fme_id_rom.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/sys_pll/sys_pll/sim/../altera_iopll_1931/sim/sys_pll_altera_iopll_1931_xxmc4ca.vo
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/sys_pll/sys_pll/sim/sys_pll.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/pr/PR_IP/sim/../altera_pr_stream_1920/sim/avst_protocol_checker.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/pr/PR_IP/sim/../altera_pr_stream_1920/sim/PR_IP_altera_pr_stream_1920_ubowtyq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/pr/PR_IP/sim/../altera_pr_ctrl_1920/sim/PR_IP_altera_pr_ctrl_1920_icmyznq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/pr/PR_IP/sim/../intel_pr_mailbox_wrapper_1911/sim/intel_pr_mailbox_wrapper.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/pr/PR_IP/sim/../altera_s10_pr_1921/sim/PR_IP_altera_s10_pr_1921_736at2y.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/pr/PR_IP/sim/PR_IP.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/user_clock/qph_user_clk_iopll_s10_RF100M/sim/../altera_iopll_1931/sim/qph_user_clk_iopll_s10_RF100M_altera_iopll_1931_vedq22q.vo
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/user_clock/qph_user_clk_iopll_s10_RF100M/sim/qph_user_clk_iopll_s10_RF100M.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/user_clock/qph_user_clk_iopll_reconfig/sim/../altera_iopll_reconfig_1940/sim/altera_iopll_reconfig_top.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/user_clock/qph_user_clk_iopll_reconfig/sim/../altera_iopll_reconfig_1940/sim/altera_iopll_reconfig_fsm.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/user_clock/qph_user_clk_iopll_reconfig/sim/../altera_iopll_reconfig_1940/sim/pulse_gen.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/user_clock/qph_user_clk_iopll_reconfig/sim/../altera_iopll_reconfig_1940/sim/shift.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/user_clock/qph_user_clk_iopll_reconfig/sim/qph_user_clk_iopll_reconfig.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/host_if/sim/../altera_axi_bridge_1931/sim/host_if_altera_axi_bridge_1931_vhmf6ra.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/host_if/sim/host_if.v
+incdir+$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../intel_st_dbg_if_120/sim/
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../intel_st_dbg_if_120/sim/synopsys/intel_st_dbg_if_csr_h.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../intel_st_dbg_if_120/sim/synopsys/intel_st_dbg_if_csr.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../intel_st_dbg_if_120/sim/synopsys/intel_st_dbg_if_dma_wrapper.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../intel_st_dbg_if_120/sim/synopsys/intel_st_dbg_if_rd_dma.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../intel_st_dbg_if_120/sim/synopsys/intel_st_dbg_if_snk.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../intel_st_dbg_if_120/sim/synopsys/intel_st_dbg_if_src.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../intel_st_dbg_if_120/sim/synopsys/intel_st_dbg_if_wr_dma.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../intel_st_dbg_if_120/sim/synopsys/intel_st_dbg_if_top.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/acl_altera_syncram_wrapped.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/acl_high_speed_fifo.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/acl_latency_one_ram_fifo.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/acl_latency_zero_ram_fifo.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/acl_lfsr.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/acl_low_latency_fifo.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/acl_mid_speed_fifo.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/acl_reset_handler.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/acl_tessellated_incr_decr_threshold.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/acl_tessellated_incr_lookahead.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/acl_zero_latency_fifo.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/hld_fifo.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_endianness_adp_100/sim/jop_blaster_avst_credit_endianness_adp_100_yas4m3a.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_w2n_101/sim/jop_blaster_avst_credit_w2n_altera_reset_controller_101_55ojt3q.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_w2n_101/sim/jop_blaster_avst_credit_w2n_101_ddx3n4q.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_ready_to_credit_102/sim/jop_blaster_avst_ready_to_credit_altera_reset_controller_102_jmw5idy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_ready_to_credit_102/sim/altera_avalon_st_pipeline_base.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_ready_to_credit_102/sim/jop_blaster_avst_ready_to_credit_102_kdygilq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../sld_hub_ctrl_core_100/sim/sld_hub_ctrl_core.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../sld_hub_ctrl_core_100/sim/sld_hub_ctrl_sld_node.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../sld_hub_ctrl_core_100/sim/sld_hub_ctrl_tck_generation.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../sld_hub_ctrl_core_100/sim/altera_streaming_sld_hub_controller_altclkctrl.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../sld_hub_ctrl_100/sim/jop_blaster_sld_hub_ctrl_100_xv4w5aa.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_endianness_adp_100/sim/jop_blaster_avst_credit_endianness_adp_100_f3ayqpy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_n2w_101/sim/jop_blaster_avst_credit_n2w_altera_reset_controller_101_qclogiy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_n2w_101/sim/pipelined_compare_eq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_n2w_101/sim/jop_blaster_avst_credit_n2w_101_j3uholy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_max_ca_101/sim/jop_blaster_avst_credit_max_ca_altera_reset_controller_101_ipp6zjy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_max_ca_101/sim/jop_blaster_avst_credit_max_ca_101_gke5fvq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/jop_blaster_avst_credit_to_ready_altera_reset_controller_102_4q6xywy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../avst_credit_to_ready_102/sim/jop_blaster_avst_credit_to_ready_102_w6eedmi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_avalon_mm_bridge_2001/sim/jop_blaster_altera_avalon_mm_bridge_2001_k2bg7dq.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_avalon_onchip_memory2_1936/sim/jop_blaster_altera_avalon_onchip_memory2_1936_gahorda.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_avalon_onchip_memory2_1936/sim/jop_blaster_altera_avalon_onchip_memory2_1936_mig5q3i.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_master_translator_191/sim/jop_blaster_altera_merlin_master_translator_191_g7h47bq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_slave_translator_191/sim/jop_blaster_altera_merlin_slave_translator_191_x56fcki.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_master_agent_191/sim/jop_blaster_altera_merlin_master_agent_191_mpbm6tq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_slave_agent_191/sim/jop_blaster_altera_merlin_slave_agent_191_ncfkfri.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_avalon_sc_fifo_1931/sim/jop_blaster_altera_avalon_sc_fifo_1931_fzgstwy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_router_1921/sim/jop_blaster_altera_merlin_router_1921_dl34hoq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_router_1921/sim/jop_blaster_altera_merlin_router_1921_kaiqbhq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_router_1921/sim/jop_blaster_altera_merlin_router_1921_pi5fqyy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_traffic_limiter_191/sim/jop_blaster_altera_merlin_traffic_limiter_altera_avalon_sc_fifo_191_mg7ilfq.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_traffic_limiter_191/sim/jop_blaster_altera_merlin_traffic_limiter_191_kcba44q.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_avalon_st_pipeline_stage_1920/sim/jop_blaster_altera_avalon_st_pipeline_stage_1920_zterisq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_burst_adapter_1923/sim/jop_blaster_altera_merlin_burst_adapter_altera_avalon_st_pipeline_stage_1923_o3km74y.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_burst_adapter_1923/sim/jop_blaster_altera_merlin_burst_adapter_1923_mtodvxa.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_demultiplexer_1921/sim/jop_blaster_altera_merlin_demultiplexer_1921_npzsnka.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_multiplexer_1921/sim/jop_blaster_altera_merlin_multiplexer_1921_mnaajgi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_demultiplexer_1921/sim/jop_blaster_altera_merlin_demultiplexer_1921_v3jph5q.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_multiplexer_1921/sim/jop_blaster_altera_merlin_multiplexer_1921_vc6vxma.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_width_adapter_1920/sim/jop_blaster_altera_merlin_width_adapter_1920_qdqoqmi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_merlin_width_adapter_1920/sim/jop_blaster_altera_merlin_width_adapter_1920_x5hnw7a.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_mm_interconnect_1920/sim/jop_blaster_altera_mm_interconnect_1920_7er7tey.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_mm_interconnect_1920/sim/jop_blaster_altera_mm_interconnect_1920_yux6jci.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_mm_interconnect_1920/sim/jop_blaster_altera_mm_interconnect_1920_wvbcyna.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../data_format_adapter_1920/sim/jop_blaster_data_format_adapter_1920_k5zstfy.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../channel_adapter_1921/sim/jop_blaster_channel_adapter_1921_ad74ixq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_avalon_st_adapter_1920/sim/jop_blaster_altera_avalon_st_adapter_1920_qi6zlvi.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../data_format_adapter_1920/sim/jop_blaster_data_format_adapter_1920_pw4k62a.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../channel_adapter_1921/sim/jop_blaster_channel_adapter_1921_mazi3uq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../altera_avalon_st_adapter_1920/sim/jop_blaster_altera_avalon_st_adapter_1920_amun2ei.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/../intel_jop_blaster_100/sim/jop_blaster_intel_jop_blaster_100_62vedcq.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/jop_blaster/sim/jop_blaster.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/remote_debug_jtag_only_clock_in/sim/remote_debug_jtag_only_clock_in.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/remote_debug_jtag_only_reset_in/sim/remote_debug_jtag_only_reset_in.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/ip/remote_debug_jtag_only/sys_clk/sim/sys_clk.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/AFU_debug/scjio_agilex/sim/../altera_sld_host_endpoint_10/sim/altera_sld_host_endpoint_wrapper.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/AFU_debug/scjio_agilex/sim/../intel_soft_core_jtag_io_10/sim/scjio_agilex_intel_soft_core_jtag_io_10_3n4smgy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/AFU_debug/scjio_agilex/sim/scjio_agilex.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/AFU_debug/config_reset_release/sim/../intel_configuration_reset_release_to_debug_logic_203/sim/intel_configuration_reset_release_to_debug_logic.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/AFU_debug/config_reset_release/sim/config_reset_release.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_axi_translator_1921/sim/remote_debug_jtag_only_altera_merlin_axi_translator_1921_uetfduq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_slave_translator_191/sim/remote_debug_jtag_only_altera_merlin_slave_translator_191_x56fcki.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_axi_master_ni_1940/sim/remote_debug_jtag_only_altera_merlin_axi_master_ni_1940_xmlitzq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_slave_agent_191/sim/remote_debug_jtag_only_altera_merlin_slave_agent_191_ncfkfri.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_avalon_sc_fifo_1931/sim/remote_debug_jtag_only_altera_avalon_sc_fifo_1931_vhmcgqy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_router_1921/sim/remote_debug_jtag_only_altera_merlin_router_1921_vcvp3bi.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_router_1921/sim/remote_debug_jtag_only_altera_merlin_router_1921_ezbunmq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_avalon_st_pipeline_stage_1920/sim/remote_debug_jtag_only_altera_avalon_st_pipeline_stage_1920_zterisq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_burst_adapter_1923/sim/remote_debug_jtag_only_altera_merlin_burst_adapter_altera_avalon_st_pipeline_stage_1923_mu2djqq.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_burst_adapter_1923/sim/remote_debug_jtag_only_altera_merlin_burst_adapter_1923_t4ieoda.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_demultiplexer_1921/sim/remote_debug_jtag_only_altera_merlin_demultiplexer_1921_e7g366y.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_multiplexer_1921/sim/remote_debug_jtag_only_altera_merlin_multiplexer_1921_blrghey.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_demultiplexer_1921/sim/remote_debug_jtag_only_altera_merlin_demultiplexer_1921_pcump4i.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_merlin_multiplexer_1921/sim/remote_debug_jtag_only_altera_merlin_multiplexer_1921_b267lna.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../hs_clk_xer_1931/sim/remote_debug_jtag_only_hs_clk_xer_1931_yh6iyey.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../hs_clk_xer_1931/sim/alt_hiconnect_clock_crosser.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../hs_clk_xer_1931/sim/alt_hiconnect_pipeline_base.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../hs_clk_xer_1931/sim/altera_std_synchronizer.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/../altera_mm_interconnect_1920/sim/remote_debug_jtag_only_altera_mm_interconnect_1920_rn44bjy.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/remote_stp/remote_debug_jtag_only/sim/remote_debug_jtag_only.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/cfg_mon/cfg_mon/sim/../altera_s10_user_rst_clkgate_1941/sim/altera_s10_user_rst_clkgate.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/cfg_mon/cfg_mon/sim/cfg_mon.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/avst_pipeline/avst_pipeline_st_pipeline_stage_0/sim/../altera_avalon_st_pipeline_stage_1920/sim/avst_pipeline_st_pipeline_stage_0_altera_avalon_st_pipeline_stage_1920_zterisq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/avst_pipeline/avst_pipeline_st_pipeline_stage_0/sim/avst_pipeline_st_pipeline_stage_0.v
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/avst_pipeline/avst_pipeline_st_pipeline_stage_1/sim/../altera_avalon_st_pipeline_stage_1920/sim/avst_pipeline_st_pipeline_stage_1_altera_avalon_st_pipeline_stage_1920_zterisq.sv
$OFS_ROOTDIR/sim/scripts/qip_gen/ofs-common/src/fpga_family/stratix10/avst_pipeline/avst_pipeline_st_pipeline_stage_1/sim/avst_pipeline_st_pipeline_stage_1.v
