# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: MIT

# TCL File Generated by Component Editor 19.2
# Wed Apr 29 23:39:33 PDT 2020
# DO NOT MODIFY


# 
# ddr_avmm_slave_endpoint "ddr_avmm_slave_endpoint" v1.0
# Intel 2020.04.29.23:39:33
# DDR AVMM Slave Endpoint
# 

# 
# request TCL package from ACDS 19.4
# 
package require -exact qsys 19.4


# 
# module ddr_avmm_slave_endpoint
# 
set_module_property DESCRIPTION "DDR AVMM Slave Endpoint"
set_module_property NAME ddr_avmm_slave_endpoint
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Interface
set_module_property AUTHOR Intel
set_module_property DISPLAY_NAME ddr_avmm_slave_endpoint
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ddr_avmm_slave_endpoint
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr_avmm_slave_endpoint.sv SYSTEM_VERILOG PATH ddr_avmm_slave_endpoint.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ddr_avmm_slave_endpoint
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr_avmm_slave_endpoint.sv SYSTEM_VERILOG PATH ddr_avmm_slave_endpoint.sv


# 
# parameters
# 
add_parameter S_ADDR_WIDTH INTEGER 27
set_parameter_property S_ADDR_WIDTH DEFAULT_VALUE 27
set_parameter_property S_ADDR_WIDTH DISPLAY_NAME S_ADDR_WIDTH
set_parameter_property S_ADDR_WIDTH ENABLED false
set_parameter_property S_ADDR_WIDTH UNITS None
set_parameter_property S_ADDR_WIDTH ALLOWED_RANGES 1:64
set_parameter_property S_ADDR_WIDTH HDL_PARAMETER true
add_parameter S_DATA_WIDTH INTEGER 1024 ""
set_parameter_property S_DATA_WIDTH DEFAULT_VALUE 1024
set_parameter_property S_DATA_WIDTH DISPLAY_NAME S_DATA_WIDTH
set_parameter_property S_DATA_WIDTH ENABLED false
set_parameter_property S_DATA_WIDTH UNITS None
set_parameter_property S_DATA_WIDTH ALLOWED_RANGES 8:1024
set_parameter_property S_DATA_WIDTH DESCRIPTION ""
set_parameter_property S_DATA_WIDTH HDL_PARAMETER true
add_parameter S_BYTEENABLE_WIDTH INTEGER 128 ""
set_parameter_property S_BYTEENABLE_WIDTH DEFAULT_VALUE 128
set_parameter_property S_BYTEENABLE_WIDTH DISPLAY_NAME S_BYTEENABLE_WIDTH
set_parameter_property S_BYTEENABLE_WIDTH ENABLED false
set_parameter_property S_BYTEENABLE_WIDTH UNITS None
set_parameter_property S_BYTEENABLE_WIDTH ALLOWED_RANGES 1:128
set_parameter_property S_BYTEENABLE_WIDTH DESCRIPTION ""
set_parameter_property S_BYTEENABLE_WIDTH HDL_PARAMETER true
add_parameter S_BURSTCOUNT_WIDTH INTEGER 7 ""
set_parameter_property S_BURSTCOUNT_WIDTH DEFAULT_VALUE 7
set_parameter_property S_BURSTCOUNT_WIDTH DISPLAY_NAME S_BURSTCOUNT_WIDTH
set_parameter_property S_BURSTCOUNT_WIDTH ENABLED false
set_parameter_property S_BURSTCOUNT_WIDTH UNITS None
set_parameter_property S_BURSTCOUNT_WIDTH ALLOWED_RANGES 7
set_parameter_property S_BURSTCOUNT_WIDTH DESCRIPTION ""
set_parameter_property S_BURSTCOUNT_WIDTH HDL_PARAMETER true
add_parameter M_ADDR_WIDTH INTEGER 27
set_parameter_property M_ADDR_WIDTH DEFAULT_VALUE 27
set_parameter_property M_ADDR_WIDTH DISPLAY_NAME M_ADDR_WIDTH
set_parameter_property M_ADDR_WIDTH ENABLED false
set_parameter_property M_ADDR_WIDTH UNITS None
set_parameter_property M_ADDR_WIDTH ALLOWED_RANGES 1:64
set_parameter_property M_ADDR_WIDTH HDL_PARAMETER true
add_parameter M_DATA_WIDTH INTEGER 576
set_parameter_property M_DATA_WIDTH DEFAULT_VALUE 576
set_parameter_property M_DATA_WIDTH DISPLAY_NAME M_DATA_WIDTH
set_parameter_property M_DATA_WIDTH ENABLED false
set_parameter_property M_DATA_WIDTH UNITS None
set_parameter_property M_DATA_WIDTH ALLOWED_RANGES 8:1024
set_parameter_property M_DATA_WIDTH HDL_PARAMETER true
add_parameter M_BYTEENABLE_WIDTH INTEGER 72
set_parameter_property M_BYTEENABLE_WIDTH DEFAULT_VALUE 72
set_parameter_property M_BYTEENABLE_WIDTH DISPLAY_NAME M_BYTEENABLE_WIDTH
set_parameter_property M_BYTEENABLE_WIDTH ENABLED false
set_parameter_property M_BYTEENABLE_WIDTH UNITS None
set_parameter_property M_BYTEENABLE_WIDTH ALLOWED_RANGES 1:128
set_parameter_property M_BYTEENABLE_WIDTH HDL_PARAMETER true
add_parameter M_BURSTCOUNT_WIDTH INTEGER 7
set_parameter_property M_BURSTCOUNT_WIDTH DEFAULT_VALUE 7
set_parameter_property M_BURSTCOUNT_WIDTH DISPLAY_NAME M_BURSTCOUNT_WIDTH
set_parameter_property M_BURSTCOUNT_WIDTH ENABLED false
set_parameter_property M_BURSTCOUNT_WIDTH UNITS None
set_parameter_property M_BURSTCOUNT_WIDTH ALLOWED_RANGES 7
set_parameter_property M_BURSTCOUNT_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point av_s0
# 
add_interface av_s0 avalon end
set_interface_property av_s0 addressGroup 0
set_interface_property av_s0 addressUnits WORDS
set_interface_property av_s0 associatedClock clock
set_interface_property av_s0 associatedReset reset
set_interface_property av_s0 bitsPerSymbol 8
set_interface_property av_s0 bridgedAddressOffset 0
set_interface_property av_s0 bridgesToMaster ""
set_interface_property av_s0 burstOnBurstBoundariesOnly false
set_interface_property av_s0 burstcountUnits WORDS
set_interface_property av_s0 explicitAddressSpan 0
set_interface_property av_s0 holdTime 0
set_interface_property av_s0 linewrapBursts false
set_interface_property av_s0 maximumPendingReadTransactions 32
set_interface_property av_s0 maximumPendingWriteTransactions 0
set_interface_property av_s0 minimumResponseLatency 1
set_interface_property av_s0 readLatency 0
set_interface_property av_s0 readWaitTime 1
set_interface_property av_s0 setupTime 0
set_interface_property av_s0 timingUnits Cycles
set_interface_property av_s0 transparentBridge false
set_interface_property av_s0 waitrequestAllowance 0
set_interface_property av_s0 writeWaitTime 0
set_interface_property av_s0 ENABLED true
set_interface_property av_s0 EXPORT_OF ""
set_interface_property av_s0 PORT_NAME_MAP ""
set_interface_property av_s0 CMSIS_SVD_VARIABLES ""
set_interface_property av_s0 SVD_ADDRESS_GROUP ""
set_interface_property av_s0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port av_s0 s0_address address Input "((S_ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port av_s0 s0_write write Input 1
add_interface_port av_s0 s0_read read Input 1
add_interface_port av_s0 s0_writedata writedata Input 1024
add_interface_port av_s0 s0_byteenable byteenable Input 128
add_interface_port av_s0 s0_burstcount burstcount Input "((S_BURSTCOUNT_WIDTH - 1)) - (0) + 1"
add_interface_port av_s0 s0_readdatavalid readdatavalid Output 1
add_interface_port av_s0 s0_readdata readdata Output 1024
add_interface_port av_s0 s0_waitrequest waitrequest Output 1
set_interface_assignment av_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment av_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment av_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment av_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point av_m0
# 
add_interface av_m0 avalon start
set_interface_property av_m0 addressGroup 0
set_interface_property av_m0 addressUnits SYMBOLS
set_interface_property av_m0 associatedClock clock
set_interface_property av_m0 associatedReset reset
set_interface_property av_m0 bitsPerSymbol 8
set_interface_property av_m0 burstOnBurstBoundariesOnly false
set_interface_property av_m0 burstcountUnits WORDS
set_interface_property av_m0 doStreamReads false
set_interface_property av_m0 doStreamWrites false
set_interface_property av_m0 holdTime 0
set_interface_property av_m0 linewrapBursts false
set_interface_property av_m0 maximumPendingReadTransactions 0
set_interface_property av_m0 maximumPendingWriteTransactions 0
set_interface_property av_m0 minimumResponseLatency 1
set_interface_property av_m0 readLatency 0
set_interface_property av_m0 readWaitTime 1
set_interface_property av_m0 setupTime 0
set_interface_property av_m0 timingUnits Cycles
set_interface_property av_m0 waitrequestAllowance 0
set_interface_property av_m0 writeWaitTime 0
set_interface_property av_m0 ENABLED true
set_interface_property av_m0 EXPORT_OF ""
set_interface_property av_m0 PORT_NAME_MAP ""
set_interface_property av_m0 CMSIS_SVD_VARIABLES ""
set_interface_property av_m0 SVD_ADDRESS_GROUP ""
set_interface_property av_m0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port av_m0 m0_address address Output "((M_ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port av_m0 m0_write write Output 1
add_interface_port av_m0 m0_read read Output 1
add_interface_port av_m0 m0_writedata writedata Output 576
add_interface_port av_m0 m0_byteenable byteenable Output "((M_BYTEENABLE_WIDTH - 1)) - (0) + 1"
add_interface_port av_m0 m0_burstcount burstcount Output "((M_BURSTCOUNT_WIDTH - 1)) - (0) + 1"
add_interface_port av_m0 m0_readdatavalid readdatavalid Input 1
add_interface_port av_m0 m0_readdata readdata Input "((M_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port av_m0 m0_waitrequest waitrequest Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges BOTH
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset reset reset Input 1

