# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: MIT

# TCL File Generated by Component Editor 19.2
# Wed Apr 29 14:07:58 PDT 2020
# DO NOT MODIFY


# 
# ddr_axi_master_endpoint "ddr_axi_master_endpoint" v1.0
# Intel 2020.04.29.14:07:58
# DDR AXI master endpoint
# 

# 
# request TCL package from ACDS 19.4
# 
package require -exact qsys 19.4


# 
# module ddr_axi_master_endpoint
# 
set_module_property DESCRIPTION "DDR AXI master endpoint"
set_module_property NAME ddr_axi_master_endpoint
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Interface
set_module_property AUTHOR Intel
set_module_property DISPLAY_NAME ddr_axi_master_endpoint
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ddr_axi_master_endpoint
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr_axi_master_endpoint.sv SYSTEM_VERILOG PATH ddr_axi_master_endpoint.sv TOP_LEVEL_FILE
add_fileset_file ofs_pipeline_reg.sv SYSTEM_VERILOG PATH ofs_pipeline_reg.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ddr_axi_master_endpoint
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr_axi_master_endpoint.sv SYSTEM_VERILOG PATH ddr_axi_master_endpoint.sv
add_fileset_file ofs_pipeline_reg.sv SYSTEM_VERILOG PATH ofs_pipeline_reg.sv


# 
# parameters
# 
add_parameter ID_WIDTH INTEGER 6 ""
set_parameter_property ID_WIDTH DEFAULT_VALUE 6
set_parameter_property ID_WIDTH DISPLAY_NAME ID_WIDTH
set_parameter_property ID_WIDTH WIDTH ""
set_parameter_property ID_WIDTH ENABLED false
set_parameter_property ID_WIDTH UNITS None
set_parameter_property ID_WIDTH ALLOWED_RANGES 1:32
set_parameter_property ID_WIDTH DESCRIPTION ""
set_parameter_property ID_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 34 ""
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 34
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH ENABLED false
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES 1:64
set_parameter_property ADDR_WIDTH DESCRIPTION ""
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 1024 ""
set_parameter_property DATA_WIDTH DEFAULT_VALUE 1024
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH ENABLED false
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES 8:1024
set_parameter_property DATA_WIDTH DESCRIPTION ""
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ACTUAL_DATA_WIDTH INTEGER 576 ""
set_parameter_property ACTUAL_DATA_WIDTH DEFAULT_VALUE 576
set_parameter_property ACTUAL_DATA_WIDTH DISPLAY_NAME ACTUAL_DATA_WIDTH
set_parameter_property ACTUAL_DATA_WIDTH ENABLED false
set_parameter_property ACTUAL_DATA_WIDTH UNITS None
set_parameter_property ACTUAL_DATA_WIDTH ALLOWED_RANGES 8:1024
set_parameter_property ACTUAL_DATA_WIDTH DESCRIPTION ""
set_parameter_property ACTUAL_DATA_WIDTH HDL_PARAMETER true
add_parameter WSTRB_WIDTH INTEGER 128 ""
set_parameter_property WSTRB_WIDTH DEFAULT_VALUE 128
set_parameter_property WSTRB_WIDTH DISPLAY_NAME WSTRB_WIDTH
set_parameter_property WSTRB_WIDTH ENABLED false
set_parameter_property WSTRB_WIDTH UNITS None
set_parameter_property WSTRB_WIDTH ALLOWED_RANGES 1:128
set_parameter_property WSTRB_WIDTH DESCRIPTION ""
set_parameter_property WSTRB_WIDTH HDL_PARAMETER true
add_parameter ACTUAL_WSTRB_WIDTH INTEGER 72 ""
set_parameter_property ACTUAL_WSTRB_WIDTH DEFAULT_VALUE 72
set_parameter_property ACTUAL_WSTRB_WIDTH DISPLAY_NAME ACTUAL_WSTRB_WIDTH
set_parameter_property ACTUAL_WSTRB_WIDTH ENABLED false
set_parameter_property ACTUAL_WSTRB_WIDTH UNITS None
set_parameter_property ACTUAL_WSTRB_WIDTH ALLOWED_RANGES 1:128
set_parameter_property ACTUAL_WSTRB_WIDTH DESCRIPTION ""
set_parameter_property ACTUAL_WSTRB_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point axi_s0_resetn
# 
add_interface axi_s0_resetn reset end
set_interface_property axi_s0_resetn associatedClock axi_s0_clk
set_interface_property axi_s0_resetn synchronousEdges BOTH
set_interface_property axi_s0_resetn ENABLED true
set_interface_property axi_s0_resetn EXPORT_OF ""
set_interface_property axi_s0_resetn PORT_NAME_MAP ""
set_interface_property axi_s0_resetn CMSIS_SVD_VARIABLES ""
set_interface_property axi_s0_resetn SVD_ADDRESS_GROUP ""
set_interface_property axi_s0_resetn IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port axi_s0_resetn axi_s0_resetn reset_n Input 1


# 
# connection point axi_s0_clk
# 
add_interface axi_s0_clk clock end
set_interface_property axi_s0_clk ENABLED true
set_interface_property axi_s0_clk EXPORT_OF ""
set_interface_property axi_s0_clk PORT_NAME_MAP ""
set_interface_property axi_s0_clk CMSIS_SVD_VARIABLES ""
set_interface_property axi_s0_clk SVD_ADDRESS_GROUP ""
set_interface_property axi_s0_clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port axi_s0_clk axi_s0_clk clk Input 1


# 
# connection point axi_m0_resetn
# 
add_interface axi_m0_resetn reset start
set_interface_property axi_m0_resetn associatedClock axi_m0_clock
set_interface_property axi_m0_resetn associatedDirectReset axi_s0_resetn
set_interface_property axi_m0_resetn associatedResetSinks axi_s0_resetn
set_interface_property axi_m0_resetn synchronousEdges BOTH
set_interface_property axi_m0_resetn ENABLED true
set_interface_property axi_m0_resetn EXPORT_OF ""
set_interface_property axi_m0_resetn PORT_NAME_MAP ""
set_interface_property axi_m0_resetn CMSIS_SVD_VARIABLES ""
set_interface_property axi_m0_resetn SVD_ADDRESS_GROUP ""
set_interface_property axi_m0_resetn IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port axi_m0_resetn axi_m0_resetn reset_n Output 1


# 
# connection point axi_m0_clock
# 
add_interface axi_m0_clock clock start
set_interface_property axi_m0_clock associatedDirectClock axi_s0_clk
set_interface_property axi_m0_clock ENABLED true
set_interface_property axi_m0_clock EXPORT_OF ""
set_interface_property axi_m0_clock PORT_NAME_MAP ""
set_interface_property axi_m0_clock CMSIS_SVD_VARIABLES ""
set_interface_property axi_m0_clock SVD_ADDRESS_GROUP ""
set_interface_property axi_m0_clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port axi_m0_clock axi_m0_clk clk Output 1


# 
# connection point axi_m0
# 
add_interface axi_m0 axi4 start
set_interface_property axi_m0 associatedClock axi_m0_clock
set_interface_property axi_m0 associatedReset axi_m0_resetn
set_interface_property axi_m0 readIssuingCapability 16
set_interface_property axi_m0 writeIssuingCapability 16
set_interface_property axi_m0 combinedIssuingCapability 16
set_interface_property axi_m0 issuesINCRBursts true
set_interface_property axi_m0 issuesWRAPBursts false
set_interface_property axi_m0 issuesFIXEDBursts false
set_interface_property axi_m0 ENABLED true
set_interface_property axi_m0 EXPORT_OF ""
set_interface_property axi_m0 PORT_NAME_MAP ""
set_interface_property axi_m0 CMSIS_SVD_VARIABLES ""
set_interface_property axi_m0 SVD_ADDRESS_GROUP ""
set_interface_property axi_m0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port axi_m0 axi_m0_awid awid Output "((ID_WIDTH - 1)) - (0) + 1"
add_interface_port axi_m0 axi_m0_awaddr awaddr Output "((ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port axi_m0 axi_m0_awlen awlen Output 8
add_interface_port axi_m0 axi_m0_awsize awsize Output 3
add_interface_port axi_m0 axi_m0_awburst awburst Output 2
add_interface_port axi_m0 axi_m0_awprot awprot Output 3
add_interface_port axi_m0 axi_m0_awvalid awvalid Output 1
add_interface_port axi_m0 axi_m0_awready awready Input 1
add_interface_port axi_m0 axi_m0_wdata wdata Output 1024
add_interface_port axi_m0 axi_m0_wstrb wstrb Output 128
add_interface_port axi_m0 axi_m0_wlast wlast Output 1
add_interface_port axi_m0 axi_m0_wvalid wvalid Output 1
add_interface_port axi_m0 axi_m0_wready wready Input 1
add_interface_port axi_m0 axi_m0_bid bid Input "((ID_WIDTH - 1)) - (0) + 1"
add_interface_port axi_m0 axi_m0_bresp bresp Input 2
add_interface_port axi_m0 axi_m0_bvalid bvalid Input 1
add_interface_port axi_m0 axi_m0_bready bready Output 1
add_interface_port axi_m0 axi_m0_arid arid Output "((ID_WIDTH - 1)) - (0) + 1"
add_interface_port axi_m0 axi_m0_araddr araddr Output "((ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port axi_m0 axi_m0_arlen arlen Output 8
add_interface_port axi_m0 axi_m0_arsize arsize Output 3
add_interface_port axi_m0 axi_m0_arburst arburst Output 2
add_interface_port axi_m0 axi_m0_arprot arprot Output 3
add_interface_port axi_m0 axi_m0_arvalid arvalid Output 1
add_interface_port axi_m0 axi_m0_arready arready Input 1
add_interface_port axi_m0 axi_m0_rid rid Input "((ID_WIDTH - 1)) - (0) + 1"
add_interface_port axi_m0 axi_m0_rdata rdata Input 1024
add_interface_port axi_m0 axi_m0_rlast rlast Input 1
add_interface_port axi_m0 axi_m0_rresp rresp Input 2
add_interface_port axi_m0 axi_m0_rvalid rvalid Input 1
add_interface_port axi_m0 axi_m0_rready rready Output 1


# 
# connection point axi_s0
# 
add_interface axi_s0 axi4 end
set_interface_property axi_s0 associatedClock axi_s0_clk
set_interface_property axi_s0 associatedReset axi_s0_resetn
set_interface_property axi_s0 readAcceptanceCapability 16
set_interface_property axi_s0 writeAcceptanceCapability 16
set_interface_property axi_s0 combinedAcceptanceCapability 16
set_interface_property axi_s0 readDataReorderingDepth 1
set_interface_property axi_s0 bridgesToMaster ""
set_interface_property axi_s0 ENABLED true
set_interface_property axi_s0 EXPORT_OF ""
set_interface_property axi_s0 PORT_NAME_MAP ""
set_interface_property axi_s0 CMSIS_SVD_VARIABLES ""
set_interface_property axi_s0 SVD_ADDRESS_GROUP ""
set_interface_property axi_s0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port axi_s0 axi_s0_awid awid Input "((ID_WIDTH - 1)) - (0) + 1"
add_interface_port axi_s0 axi_s0_awaddr awaddr Input "((ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port axi_s0 axi_s0_awlen awlen Input 8
add_interface_port axi_s0 axi_s0_awsize awsize Input 3
add_interface_port axi_s0 axi_s0_awburst awburst Input 2
add_interface_port axi_s0 axi_s0_awvalid awvalid Input 1
add_interface_port axi_s0 axi_s0_awready awready Output 1
add_interface_port axi_s0 axi_s0_wdata wdata Input "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port axi_s0 axi_s0_wstrb wstrb Input "((WSTRB_WIDTH - 1)) - (0) + 1"
add_interface_port axi_s0 axi_s0_wlast wlast Input 1
add_interface_port axi_s0 axi_s0_wvalid wvalid Input 1
add_interface_port axi_s0 axi_s0_wready wready Output 1
add_interface_port axi_s0 axi_s0_bid bid Output "((ID_WIDTH - 1)) - (0) + 1"
add_interface_port axi_s0 axi_s0_bresp bresp Output 2
add_interface_port axi_s0 axi_s0_bvalid bvalid Output 1
add_interface_port axi_s0 axi_s0_bready bready Input 1
add_interface_port axi_s0 axi_s0_arid arid Input "((ID_WIDTH - 1)) - (0) + 1"
add_interface_port axi_s0 axi_s0_araddr araddr Input "((ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port axi_s0 axi_s0_arlen arlen Input 8
add_interface_port axi_s0 axi_s0_arsize arsize Input 3
add_interface_port axi_s0 axi_s0_arburst arburst Input 2
add_interface_port axi_s0 axi_s0_arvalid arvalid Input 1
add_interface_port axi_s0 axi_s0_arready arready Output 1
add_interface_port axi_s0 axi_s0_rid rid Output "((ID_WIDTH - 1)) - (0) + 1"
add_interface_port axi_s0 axi_s0_rdata rdata Output "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port axi_s0 axi_s0_rlast rlast Output 1
add_interface_port axi_s0 axi_s0_rresp rresp Output 2
add_interface_port axi_s0 axi_s0_rvalid rvalid Output 1
add_interface_port axi_s0 axi_s0_rready rready Input 1

