// Copyright 2021 Intel Corporation
// SPDX-License-Identifier: MIT

//-----------------------------------------------------------------------------
// Description : 
// class he_mem_user_intr_seq.svh is executed by he_mem_user_intr_test 
// This sequence verifies the functionality of the user interrputs  
// The interrupt is generated by forcing/ writing the error register .
// PBA mechanism is verified using masking and un-masking the interrupt vector
// Sequence is running on virtual_sequencer 
//-----------------------------------------------------------------------------

`ifndef HE_MEM_USER_INTR_SEQ_SVH
`define HE_MEM_USER_INTR_SEQ_SVH

class he_mem_user_intr_seq extends he_user_intr_seq;
    `uvm_object_utils(he_mem_user_intr_seq)
    `uvm_declare_p_sequencer(virtual_sequencer)

    constraint he_mem_c { he_mem == 1; }

    function new(string name = "he_mem_user_intr_seq");
        super.new(name);
    endfunction : new


endclass : he_mem_user_intr_seq

`endif // HE_MEM_USER_INTR_SEQ_SVH
